#pragma once

#include <string>
#include <array>
#include <vector>

enum ECstrike15UserMessages
{
    CS_UM_VGUIMenu = 1,
    CS_UM_Geiger = 2,
    CS_UM_Train = 3,
    CS_UM_HudText = 4,
    CS_UM_SayText = 5,
    CS_UM_SayText2 = 6,
    CS_UM_TextMsg = 7,
    CS_UM_HudMsg = 8,
    CS_UM_ResetHud = 9,
    CS_UM_GameTitle = 10,
    CS_UM_Shake = 12,
    CS_UM_Fade = 13,
    CS_UM_Rumble = 14,
    CS_UM_CloseCaption = 15,
    CS_UM_CloseCaptionDirect = 16,
    CS_UM_SendAudio = 17,
    CS_UM_RawAudio = 18,
    CS_UM_VoiceMask = 19,
    CS_UM_RequestState = 20,
    CS_UM_Damage = 21,
    CS_UM_RadioText = 22,
    CS_UM_HintText = 23,
    CS_UM_KeyHintText = 24,
    CS_UM_ProcessSpottedEntityUpdate = 25,
    CS_UM_ReloadEffect = 26,
    CS_UM_AdjustMoney = 27,
    CS_UM_UpdateTeamMoney = 28,
    CS_UM_StopSpectatorMode = 29,
    CS_UM_KillCam = 30,
    CS_UM_DesiredTimescale = 31,
    CS_UM_CurrentTimescale = 32,
    CS_UM_AchievementEvent = 33,
    CS_UM_MatchEndConditions = 34,
    CS_UM_DisconnectToLobby = 35,
    CS_UM_PlayerStatsUpdate = 36,
    CS_UM_DisplayInventory = 37,
    CS_UM_WarmupHasEnded = 38,
    CS_UM_ClientInfo = 39,
    CS_UM_XRankGet = 40,
    CS_UM_XRankUpd = 41,
    CS_UM_CallVoteFailed = 45,
    CS_UM_VoteStart = 46,
    CS_UM_VotePass = 47,
    CS_UM_VoteFailed = 48,
    CS_UM_VoteSetup = 49,
    CS_UM_ServerRankRevealAll = 50,
    CS_UM_SendLastKillerDamageToClient = 51,
    CS_UM_ServerRankUpdate = 52,
    CS_UM_ItemPickup = 53,
    CS_UM_ShowMenu = 54,
    CS_UM_BarTime = 55,
    CS_UM_AmmoDenied = 56,
    CS_UM_MarkAchievement = 57,
    CS_UM_MatchStatsUpdate = 58,
    CS_UM_ItemDrop = 59,
    CS_UM_GlowPropTurnOff = 60,
    CS_UM_SendPlayerItemDrops = 61,
    CS_UM_RoundBackupFilenames = 62,
    CS_UM_SendPlayerItemFound = 63,
    CS_UM_ReportHit = 64,
    CS_UM_XpUpdate = 65,
    CS_UM_QuestProgress = 66,
    CS_UM_ScoreLeaderboardData = 67,
    CS_UM_PlayerDecalDigitalSignature = 68,
    MAX_ECSTRIKE15USERMESSAGES
};

enum EItemDefinitionIndex
{
	WEAPON_DEAGLE = 1,
	WEAPON_ELITE = 2,
	WEAPON_FIVESEVEN = 3,
	WEAPON_GLOCK = 4,
	WEAPON_AK47 = 7,
	WEAPON_AUG = 8,
	WEAPON_AWP = 9,
	WEAPON_FAMAS = 10,
	WEAPON_G3SG1 = 11,
	WEAPON_GALILAR = 13,
	WEAPON_M249 = 14,
	WEAPON_M4A1 = 16,
	WEAPON_MAC10 = 17,
	WEAPON_P90 = 19,
	WEAPON_MP5SD = 23,
	WEAPON_UMP45 = 24,
	WEAPON_XM1014 = 25,
	WEAPON_BIZON = 26,
	WEAPON_MAG7 = 27,
	WEAPON_NEGEV = 28,
	WEAPON_SAWEDOFF = 29,
	WEAPON_TEC9 = 30,
	WEAPON_TASER = 31,
	WEAPON_HKP2000 = 32,
	WEAPON_MP7 = 33,
	WEAPON_MP9 = 34,
	WEAPON_NOVA = 35,
	WEAPON_P250 = 36,
	WEAPON_SCAR20 = 38,
	WEAPON_SG556 = 39,
	WEAPON_SSG08 = 40,
	WEAPON_KNIFE = 42,
	WEAPON_FLASHBANG = 43,
	WEAPON_HEGRENADE = 44,
	WEAPON_SMOKEGRENADE = 45,
	WEAPON_MOLOTOV = 46,
	WEAPON_DECOY = 47,
	WEAPON_INCGRENADE = 48,
	WEAPON_C4 = 49,
	WEAPON_KNIFE_T = 59,
	WEAPON_M4A1_SILENCER = 60,
	WEAPON_USP_SILENCER = 61,
	WEAPON_CZ75A = 63,
	WEAPON_REVOLVER = 64,
	WEAPON_TAGRENADE = 68,
	WEAPON_KNIFE_BAYONET = 500,
	WEAPON_KNIFE_FLIP = 505,
	WEAPON_KNIFE_GUT = 506,
	WEAPON_KNIFE_KARAMBIT = 507,
	WEAPON_KNIFE_M9_BAYONET = 508,
	WEAPON_KNIFE_TACTICAL = 509,
	WEAPON_KNIFE_FALCHION = 512,
	WEAPON_KNIFE_SURVIVAL_BOWIE = 514,
	WEAPON_KNIFE_BUTTERFLY = 515,
	WEAPON_KNIFE_PUSH = 516,
	WEAPON_KNIFE_URSUS = 519,
	WEAPON_KNIFE_GYPSY_JACKKNIFE = 520,
	WEAPON_KNIFE_STILETTO = 522,
	WEAPON_KNIFE_WIDOWMAKER = 523,
	GLOVE_STUDDED_BLOODHOUND = 5027,
	GLOVE_T_SIDE = 5028,
	GLOVE_CT_SIDE = 5029,
	GLOVE_SPORTY = 5030,
	GLOVE_SLICK = 5031,
	GLOVE_LEATHER_WRAP = 5032,
	GLOVE_MOTORCYCLE = 5033,
	GLOVE_SPECIALIST = 5034,
	GLOVE_HYDRA = 5035
};

enum EClassId
{
	CTestTraceline = 217,
	CTEWorldDecal = 218,
	CTESpriteSpray = 215,
	CTESprite = 214,
	CTESparks = 213,
	CTESmoke = 212,
	CTEShowLine = 210,
	CTEProjectedDecal = 207,
	CFEPlayerDecal = 69,
	CTEPlayerDecal = 206,
	CTEPhysicsProp = 203,
	CTEParticleSystem = 202,
	CTEMuzzleFlash = 201,
	CTELargeFunnel = 199,
	CTEKillPlayerAttachments = 198,
	CTEImpact = 197,
	CTEGlowSprite = 196,
	CTEShatterSurface = 209,
	CTEFootprintDecal = 193,
	CTEFizz = 192,
	CTEExplosion = 190,
	CTEEnergySplash = 189,
	CTEEffectDispatch = 188,
	CTEDynamicLight = 187,
	CTEDecal = 185,
	CTEClientProjectile = 184,
	CTEBubbleTrail = 183,
	CTEBubbles = 182,
	CTEBSPDecal = 181,
	CTEBreakModel = 180,
	CTEBloodStream = 179,
	CTEBloodSprite = 178,
	CTEBeamSpline = 177,
	CTEBeamRingPoint = 176,
	CTEBeamRing = 175,
	CTEBeamPoints = 174,
	CTEBeamLaser = 173,
	CTEBeamFollow = 172,
	CTEBeamEnts = 171,
	CTEBeamEntPoint = 170,
	CTEBaseBeam = 169,
	CTEArmorRicochet = 168,
	CTEMetalSparks = 200,
	CSteamJet = 161,
	CSmokeStack = 154,
	DustTrail = 268,
	CFireTrail = 72,
	SporeTrail = 274,
	SporeExplosion = 273,
	RocketTrail = 271,
	SmokeTrail = 272,
	CPropVehicleDriveable = 141,
	ParticleSmokeGrenade = 270,
	CParticleFire = 114,
	MovieExplosion = 269,
	CTEGaussExplosion = 195,
	CEnvQuadraticBeam = 64,
	CEmbers = 53,
	CEnvWind = 68,
	CPrecipitation = 134,
	CPrecipitationBlocker = 135,
	CBaseTempEntity = 18,
	NextBotCombatCharacter = 0,
	CEconWearable = 52,
	CBaseAttributableItem = 4,
	CEconEntity = 51,
	CWeaponXM1014 = 265,
	CWeaponTaser = 260,
	CTablet = 165,
	CSmokeGrenade = 152,
	CWeaponSG552 = 257,
	CSensorGrenade = 148,
	CWeaponSawedoff = 253,
	CWeaponNOVA = 249,
	CIncendiaryGrenade = 97,
	CMolotovGrenade = 110,
	CMelee = 109,
	CWeaponM3 = 241,
	CKnifeGG = 106,
	CKnife = 105,
	CHEGrenade = 94,
	CFlashbang = 75,
	CFists = 74,
	CWeaponElite = 232,
	CDecoyGrenade = 45,
	CDEagle = 44,
	CWeaponUSP = 264,
	CWeaponM249 = 240,
	CWeaponUMP45 = 263,
	CWeaponTMP = 262,
	CWeaponTec9 = 261,
	CWeaponSSG08 = 259,
	CWeaponSG556 = 258,
	CWeaponSG550 = 256,
	CWeaponScout = 255,
	CWeaponSCAR20 = 254,
	CSCAR17 = 146,
	CWeaponP90 = 252,
	CWeaponP250 = 251,
	CWeaponP228 = 250,
	CWeaponNegev = 248,
	CWeaponMP9 = 247,
	CWeaponMP7 = 246,
	CWeaponMP5Navy = 245,
	CWeaponMag7 = 244,
	CWeaponMAC10 = 243,
	CWeaponM4A1 = 242,
	CWeaponHKP2000 = 239,
	CWeaponGlock = 238,
	CWeaponGalilAR = 237,
	CWeaponGalil = 236,
	CWeaponG3SG1 = 235,
	CWeaponFiveSeven = 234,
	CWeaponFamas = 233,
	CWeaponBizon = 228,
	CWeaponAWP = 226,
	CWeaponAug = 225,
	CAK47 = 1,
	CWeaponCSBaseGun = 230,
	CWeaponCSBase = 229,
	CC4 = 32,
	CBreachCharge = 28,
	CBreachChargeProjectile = 29,
	CWeaponBaseItem = 227,
	CBaseCSGrenade = 8,
	CSmokeGrenadeProjectile = 153,
	CSensorGrenadeProjectile = 149,
	CMolotovProjectile = 111,
	CItem_Healthshot = 102,
	CItemDogtags = 104,
	CDecoyProjectile = 46,
	CPhysPropRadarJammer = 124,
	CPhysPropWeaponUpgrade = 125,
	CPhysPropAmmoBox = 122,
	CPhysPropLootCrate = 123,
	CItemCash = 103,
	CEnvGasCanister = 61,
	CDronegun = 48,
	CParadropChopper = 113,
	CSurvivalSpawnChopper = 164,
	CBRC4Target = 27,
	CInfoMapRegion = 100,
	CFireCrackerBlast = 70,
	CInferno = 98,
	CChicken = 34,
	CDrone = 47,
	CFootstepControl = 77,
	CCSGameRulesProxy = 37,
	CWeaponCubemap = 0,
	CWeaponCycler = 231,
	CTEPlantBomb = 204,
	CTEFireBullets = 191,
	CTERadioIcon = 208,
	CPlantedC4 = 126,
	CCSTeam = 41,
	CCSPlayerResource = 39,
	CCSPlayer = 38,
	CCSRagdoll = 40,
	CTEPlayerAnimEvent = 205,
	CHostage = 95,
	CHostageCarriableProp = 96,
	CBaseCSGrenadeProjectile = 9,
	CHandleTest = 93,
	CTeamplayRoundBasedRulesProxy = 167,
	CSpriteTrail = 159,
	CSpriteOriented = 158,
	CSprite = 157,
	CRagdollPropAttached = 144,
	CRagdollProp = 143,
	CPropCounter = 138,
	CPredictedViewModel = 136,
	CPoseController = 132,
	CGrassBurn = 92,
	CGameRulesProxy = 91,
	CInfoLadderDismount = 99,
	CFuncLadder = 83,
	CTEFoundryHelpers = 194,
	CEnvDetailController = 59,
	CDangerZone = 42,
	CDangerZoneController = 43,
	CWorldVguiText = 267,
	CWorld = 266,
	CWaterLODControl = 224,
	CWaterBullet = 223,
	CVoteController = 222,
	CVGuiScreen = 221,
	CPropJeep = 140,
	CPropVehicleChoreoGeneric = 0,
	CTriggerSoundOperator = 220,
	CBaseVPhysicsTrigger = 22,
	CTriggerPlayerMovement = 219,
	CBaseTrigger = 20,
	CTest_ProxyToggle_Networkable = 216,
	CTesla = 211,
	CBaseTeamObjectiveResource = 17,
	CTeam = 166,
	CSunlightShadowControl = 163,
	CSun = 162,
	CParticlePerformanceMonitor = 115,
	CSpotlightEnd = 156,
	CSpatialEntity = 155,
	CSlideshowDisplay = 151,
	CShadowControl = 150,
	CSceneEntity = 147,
	CRopeKeyframe = 145,
	CRagdollManager = 142,
	CPhysicsPropMultiplayer = 120,
	CPhysBoxMultiplayer = 118,
	CPropDoorRotating = 139,
	CBasePropDoor = 16,
	CDynamicProp = 50,
	CProp_Hallucination = 137,
	CPostProcessController = 133,
	CPointWorldText = 131,
	CPointCommentaryNode = 130,
	CPointCamera = 129,
	CPlayerResource = 128,
	CPlasma = 127,
	CPhysMagnet = 121,
	CPhysicsProp = 119,
	CStatueProp = 160,
	CPhysBox = 117,
	CParticleSystem = 116,
	CMovieDisplay = 112,
	CMaterialModifyControl = 108,
	CLightGlow = 107,
	CItemAssaultSuitUseable = 0,
	CItem = 0,
	CInfoOverlayAccessor = 101,
	CFuncTrackTrain = 90,
	CFuncSmokeVolume = 89,
	CFuncRotating = 88,
	CFuncReflectiveGlass = 87,
	CFuncOccluder = 86,
	CFuncMoveLinear = 85,
	CFuncMonitor = 84,
	CFunc_LOD = 79,
	CTEDust = 186,
	CFunc_Dust = 78,
	CFuncConveyor = 82,
	CFuncBrush = 81,
	CBreakableSurface = 31,
	CFuncAreaPortalWindow = 80,
	CFish = 73,
	CFireSmoke = 71,
	CEnvTonemapController = 67,
	CEnvScreenEffect = 65,
	CEnvScreenOverlay = 66,
	CEnvProjectedTexture = 63,
	CEnvParticleScript = 62,
	CFogController = 76,
	CEnvDOFController = 60,
	CCascadeLight = 33,
	CEnvAmbientLight = 58,
	CEntityParticleTrail = 57,
	CEntityFreezing = 56,
	CEntityFlame = 55,
	CEntityDissolve = 54,
	CDynamicLight = 49,
	CColorCorrectionVolume = 36,
	CColorCorrection = 35,
	CBreakableProp = 30,
	CBeamSpotlight = 25,
	CBaseButton = 5,
	CBaseToggle = 19,
	CBasePlayer = 15,
	CBaseFlex = 12,
	CBaseEntity = 11,
	CBaseDoor = 10,
	CBaseCombatCharacter = 6,
	CBaseAnimatingOverlay = 3,
	CBoneFollower = 26,
	CBaseAnimating = 2,
	CAI_BaseNPC = 0,
	CBeam = 24,
	CBaseViewModel = 21,
	CBaseParticleEntity = 14,
	CBaseGrenade = 13,
	CBaseCombatWeapon = 7,
	CBaseWeaponWorldModel = 23
};

enum ECSPlayerBone
{
    PELVIS = 0,
    SPINE_0,
    SPINE_1,
    SPINE_2,
    SPINE_3,
    NECK_0,
    HEAD_0,
    CLAVICLE_L,
    ARM_UPPER_L,
    ARM_LOWER_L,
    HAND_L,
    FINGER_MIDDLE_META_L,
    FINGER_MIDDLE_0_L,
    FINGER_MIDDLE_1_L,
    FINGER_MIDDLE_2_L,
    FINGER_PINKY_META_L,
    FINGER_PINKY_0_L,
    FINGER_PINKY_1_L,
    FINGER_PINKY_2_L,
    FINGER_INDEX_META_L,
    FINGER_INDEX_0_L,
    FINGER_INDEX_1_L,
    FINGER_INDEX_2_L,
    FINGER_THUMB_0_L,
    FINGER_THUMB_1_L,
    FINGER_THUMB_2_L,
    FINGER_RING_META_L,
    FINGER_RING_0_L,
    FINGER_RING_1_L,
    FINGER_RING_2_L,
    WEAPON_HAND_L,
    ARM_LOWER_L_TWIST,
    ARM_LOWER_L_TWIST1,
    ARM_UPPER_L_TWIST,
    ARM_UPPER_L_TWIST1,
    CLAVICLE_R,
    ARM_UPPER_R,
    ARM_LOWER_R,
    HAND_R,
    FINGER_MIDDLE_META_R,
    FINGER_MIDDLE_0_R,
    FINGER_MIDDLE_1_R,
    FINGER_MIDDLE_2_R,
    FINGER_PINKY_META_R,
    FINGER_PINKY_0_R,
    FINGER_PINKY_1_R,
    FINGER_PINKY_2_R,
    FINGER_INDEX_META_R,
    FINGER_INDEX_0_R,
    FINGER_INDEX_1_R,
    FINGER_INDEX_2_R,
    FINGER_THUMB_0_R,
    FINGER_THUMB_1_R,
    FINGER_THUMB_2_R,
    FINGER_RING_META_R,
    FINGER_RING_0_R,
    FINGER_RING_1_R,
    FINGER_RING_2_R,
    WEAPON_HAND_R,
    ARM_LOWER_R_TWIST,
    ARM_LOWER_R_TWIST1,
    ARM_UPPER_R_TWIST,
    ARM_UPPER_R_TWIST1,
    LEG_UPPER_L,
    LEG_LOWER_L,
    ANKLE_L,
    BALL_L,
    LFOOT_LOCK,
    LEG_UPPER_L_TWIST,
    LEG_UPPER_L_TWIST1,
    LEG_UPPER_R,
    LEG_LOWER_R,
    ANKLE_R,
    BALL_R,
    RFOOT_LOCK,
    LEG_UPPER_R_TWIST,
    LEG_UPPER_R_TWIST1,
    FINGER_PINKY_L_END,
    FINGER_PINKY_R_END,
    VALVEBIPED_WEAPON_BONE,
    LH_IK_DRIVER,
    PRIMARY_JIGGLE_JNT,
    MAX_ECSPLAYERBONES
};

enum EEntityFlag
{
    FL_ONGROUND = (1 << 0),
    FL_DUCKING = (1 << 1),
    FL_WATERJUMP = (1 << 2),
    FL_ONTRAIN = (1 << 3),
    FL_INRAIN = (1 << 4),
    FL_FROZEN = (1 << 5),
    FL_ATCONTROLS = (1 << 6),
    FL_CLIENT = (1 << 7),
    FL_FAKECLIENT = (1 << 8),
    MAX_ENTITYFLAGS
};

enum ELifeState : unsigned char
{
    LIFE_ALIVE = 0,// alive
    LIFE_DYING = 1, // playing death animation or still falling off of a ledge waiting to hit ground
    LIFE_DEAD = 2, // dead. lying still.
    MAX_LIFESTATE
};

enum EWeaponSound
{
    EMPTY,
    SINGLE,
    SINGLE_NPC,
    WPN_DOUBLE, // Can't be "DOUBLE" because windows.h uses it.
    DOUBLE_NPC,
    BURST,
    RELOAD,
    RELOAD_NPC,
    MELEE_MISS,
    MELEE_HIT,
    MELEE_HIT_WORLD,
    SPECIAL1,
    SPECIAL2,
    SPECIAL3,
    TAUNT,
    FAST_RELOAD,
    // Add new shoot sound types here
    REVERSE_THE_NEW_SOUND,
    NUM_SHOOT_SOUND_TYPES,
    MAX_WEAPONSOUND
};

enum EMoveType
{
    MOVETYPE_NONE = 0,
    MOVETYPE_ISOMETRIC,
    MOVETYPE_WALK,
    MOVETYPE_STEP,
    MOVETYPE_FLY,
    MOVETYPE_FLYGRAVITY,
    MOVETYPE_VPHYSICS,
    MOVETYPE_PUSH,
    MOVETYPE_NOCLIP,
    MOVETYPE_LADDER,
    MOVETYPE_OBSERVER,
    MOVETYPE_CUSTOM,
    MOVETYPE_LAST = MOVETYPE_CUSTOM,
    MOVETYPE_MAX_BITS = 4,
    MAX_MOVETYPE
};

enum EClientFrameStage : int
{
	FRAME_UNDEFINED = -1,
	FRAME_START,
	FRAME_NET_UPDATE_START,
	FRAME_NET_UPDATE_POSTDATAUPDATE_START,
	FRAME_NET_UPDATE_POSTDATAUPDATE_END,
	FRAME_NET_UPDATE_END,
	FRAME_RENDER_START,
	FRAME_RENDER_END
};

enum EMaterialVarFlag
{
	MATERIAL_VAR_DEBUG = (1 << 0),
	MATERIAL_VAR_NO_DEBUG_OVERRIDE = (1 << 1),
	MATERIAL_VAR_NO_DRAW = (1 << 2),
	MATERIAL_VAR_USE_IN_FILLRATE_MODE = (1 << 3),
	MATERIAL_VAR_VERTEXCOLOR = (1 << 4),
	MATERIAL_VAR_VERTEXALPHA = (1 << 5),
	MATERIAL_VAR_SELFILLUM = (1 << 6),
	MATERIAL_VAR_ADDITIVE = (1 << 7),
	MATERIAL_VAR_ALPHATEST = (1 << 8),
	//MATERIAL_VAR_UNUSED = (1 << 9),
	MATERIAL_VAR_ZNEARER = (1 << 10),
	MATERIAL_VAR_MODEL = (1 << 11),
	MATERIAL_VAR_FLAT = (1 << 12),
	MATERIAL_VAR_NOCULL = (1 << 13),
	MATERIAL_VAR_NOFOG = (1 << 14),
	MATERIAL_VAR_IGNOREZ = (1 << 15),
	MATERIAL_VAR_DECAL = (1 << 16),
	MATERIAL_VAR_ENVMAPSPHERE = (1 << 17), // OBSOLETE
	MATERIAL_VAR_UNUSED = (1 << 18), // UNUSED
	MATERIAL_VAR_ENVMAPCAMERASPACE = (1 << 19), // OBSOLETE
	MATERIAL_VAR_BASEALPHAENVMAPMASK = (1 << 20),
	MATERIAL_VAR_TRANSLUCENT = (1 << 21),
	MATERIAL_VAR_NORMALMAPALPHAENVMAPMASK = (1 << 22),
	MATERIAL_VAR_NEEDS_SOFTWARE_SKINNING = (1 << 23), // OBSOLETE
	MATERIAL_VAR_OPAQUETEXTURE = (1 << 24),
	MATERIAL_VAR_ENVMAPMODE = (1 << 25), // OBSOLETE
	MATERIAL_VAR_SUPPRESS_DECALS = (1 << 26),
	MATERIAL_VAR_HALFLAMBERT = (1 << 27),
	MATERIAL_VAR_WIREFRAME = (1 << 28),
	MATERIAL_VAR_ALLOWALPHATOCOVERAGE = (1 << 29),
	MATERIAL_VAR_ALPHA_MODIFIED_BY_PROXY = (1 << 30),
	MATERIAL_VAR_VERTEXFOG = (1 << 31),
};

enum EBoxType : int
{
	Normal = 0,
	Corner
};

enum ELanguage : int
{
	English = 0,
	Russian
};

enum ESequence
{
	SEQUENCE_DEFAULT_DRAW = 0,
	SEQUENCE_DEFAULT_IDLE1 = 1,
	SEQUENCE_DEFAULT_IDLE2 = 2,
	SEQUENCE_DEFAULT_LIGHT_MISS1 = 3,
	SEQUENCE_DEFAULT_LIGHT_MISS2 = 4,
	SEQUENCE_DEFAULT_HEAVY_MISS1 = 9,
	SEQUENCE_DEFAULT_HEAVY_HIT1 = 10,
	SEQUENCE_DEFAULT_HEAVY_BACKSTAB = 11,
	SEQUENCE_DEFAULT_LOOKAT01 = 12,

	SEQUENCE_BUTTERFLY_DRAW = 0,
	SEQUENCE_BUTTERFLY_DRAW2 = 1,
	SEQUENCE_BUTTERFLY_LOOKAT01 = 13,
	SEQUENCE_BUTTERFLY_LOOKAT02 = 14,
	SEQUENCE_BUTTERFLY_LOOKAT03 = 15,

	SEQUENCE_FALCHION_IDLE1 = 1,
	SEQUENCE_FALCHION_HEAVY_MISS1 = 8,
	SEQUENCE_FALCHION_HEAVY_MISS1_NOFLIP = 9,
	SEQUENCE_FALCHION_LOOKAT01 = 12,
	SEQUENCE_FALCHION_LOOKAT02 = 13,

	SEQUENCE_DAGGERS_IDLE1 = 1,
	SEQUENCE_DAGGERS_LIGHT_MISS1 = 2,
	SEQUENCE_DAGGERS_LIGHT_MISS5 = 6,
	SEQUENCE_DAGGERS_HEAVY_MISS2 = 11,
	SEQUENCE_DAGGERS_HEAVY_MISS1 = 12,

	SEQUENCE_BOWIE_IDLE1 = 1,
};

enum team : int
{
	team_spec = 1,
	team_t = 2,
	team_ct = 3
};

struct sticker_setting
{
	int kit_index = 0;
	int kit_vector_index = 0;
	float wear = std::numeric_limits<float>::min();
	float scale = 1.f;
	float rotation = 0.f;
};

struct item_setting
{
	bool enabled = false;
	char name[32] = "Default";
	int definition_index = 1;
	int paint_kit_index = 0;
	int definition_override_index = 0;
	int seed = 0;
	struct
	{
		bool enabled = false;
		int counter = 0;
	} stat_track;

	float wear = std::numeric_limits<float>::min();
	char custom_name[32] = "";
	std::array<sticker_setting, 5> stickers;
};

struct weapon_kit_t
{
	int index;
	std::string rarity;
};

struct paint_kit_t
{
	int id;
	std::string english;
	std::string russian;
	std::vector<weapon_kit_t> weapons;
};

struct weapon_info_t
{
	constexpr weapon_info_t(const char* model, const char* icon = nullptr) :
		model(model),
		icon(icon)
	{}
	const char* model;
	const char* icon;
};

struct weapon_name_t
{
	constexpr weapon_name_t(const int definition_index, const char* name) :
		definition_index(definition_index),
		name(name)
	{}
	int definition_index = 0;
	const char* name = nullptr;
};